Tahoe\CredentialBundle\Entity\Credential:
    type: entity
    table: th_cr_credential
    repositoryClass: Tahoe\CredentialBundle\Repository\CredentialRepository
    indexes:
        id_write_token_idx:
            columns: [id, writeToken]
        id_read_token_idx:
            columns: [id, readToken]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        writeToken:
            name: write_token
            type: string
        readToken:
            name: read_token
            type: string
        data:
            type: json_array
    lifecycleCallbacks: {  }
